/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aldob
 */
public class AdminDrinkScreen extends javax.swing.JFrame {

    /**
     * Creates new form DrinkScreen
     */
    CrudMenuDrink crudDrink = new CrudMenuDrink();
    DefaultTableModel model;

    public AdminDrinkScreen() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) drinkTable.getModel();
        selectDrinks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        username2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        username3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idDrink = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        drinkName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        drinkPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        drinkCategories = new javax.swing.JComboBox<>();
        btnDrinkDelete = new javax.swing.JButton();
        btnDrinkClear = new javax.swing.JButton();
        btnDrinkEdit = new javax.swing.JButton();
        btnDrinkAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        drinkTable = new javax.swing.JTable();
        drinkStock = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dashboard1 = new javax.swing.JLabel();
        manageUser1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        foodMenu1 = new javax.swing.JLabel();
        drinkMenu1 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Username");

        username2.setBackground(new java.awt.Color(232, 251, 255));
        username2.setForeground(new java.awt.Color(102, 102, 102));
        username2.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Username");

        username3.setBackground(new java.awt.Color(232, 251, 255));
        username3.setForeground(new java.awt.Color(102, 102, 102));
        username3.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(8, 126, 78));

        jPanel2.setBackground(new java.awt.Color(238, 238, 238));
        jPanel2.setForeground(new java.awt.Color(205, 205, 205));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Menu Minuman");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Kode Minuman");

        idDrink.setBackground(new java.awt.Color(255, 255, 255));
        idDrink.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idDrink.setForeground(new java.awt.Color(0, 0, 0));
        idDrink.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nama");

        drinkName.setBackground(new java.awt.Color(255, 255, 255));
        drinkName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        drinkName.setForeground(new java.awt.Color(0, 0, 0));
        drinkName.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Harga");

        drinkPrice.setBackground(new java.awt.Color(255, 255, 255));
        drinkPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        drinkPrice.setForeground(new java.awt.Color(0, 0, 0));
        drinkPrice.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Kategori");

        drinkCategories.setBackground(new java.awt.Color(255, 255, 255));
        drinkCategories.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        drinkCategories.setForeground(new java.awt.Color(102, 102, 102));
        drinkCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teh", "Susu", "Kopi", "Jus" }));
        drinkCategories.setBorder(null);
        drinkCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkCategoriesActionPerformed(evt);
            }
        });

        btnDrinkDelete.setBackground(new java.awt.Color(8, 126, 78));
        btnDrinkDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDrinkDelete.setText("Delete");
        btnDrinkDelete.setBorderPainted(false);
        btnDrinkDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkDeleteActionPerformed(evt);
            }
        });

        btnDrinkClear.setBackground(new java.awt.Color(8, 126, 78));
        btnDrinkClear.setForeground(new java.awt.Color(255, 255, 255));
        btnDrinkClear.setText("Clear");
        btnDrinkClear.setBorderPainted(false);
        btnDrinkClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkClearActionPerformed(evt);
            }
        });

        btnDrinkEdit.setBackground(new java.awt.Color(8, 126, 78));
        btnDrinkEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnDrinkEdit.setText("Ubah");
        btnDrinkEdit.setBorderPainted(false);
        btnDrinkEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkEditActionPerformed(evt);
            }
        });

        btnDrinkAdd.setBackground(new java.awt.Color(8, 126, 78));
        btnDrinkAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnDrinkAdd.setText("Tambah");
        btnDrinkAdd.setBorderPainted(false);
        btnDrinkAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkAddActionPerformed(evt);
            }
        });

        drinkTable.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        drinkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Minuman", "Nama", "Stock", "Harga", "Kategori"
            }
        ));
        drinkTable.setRowHeight(25);
        drinkTable.setSelectionBackground(new java.awt.Color(8, 126, 78));
        drinkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinkTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drinkTable);

        drinkStock.setBackground(new java.awt.Color(255, 255, 255));
        drinkStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        drinkStock.setForeground(new java.awt.Color(102, 102, 102));
        drinkStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Tersedia" }));
        drinkStock.setBorder(null);
        drinkStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkStockActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Stok");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(drinkCategories, javax.swing.GroupLayout.Alignment.LEADING, 0, 295, Short.MAX_VALUE)
                                        .addComponent(drinkName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idDrink, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drinkPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(drinkStock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(150, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDrinkAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDrinkEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDrinkDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDrinkClear)))
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drinkName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drinkPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinkCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDrinkDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDrinkClear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDrinkAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDrinkEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lobster", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PB");

        jButton1.setBackground(new java.awt.Color(8, 126, 78));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dashboard1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboard1.setForeground(new java.awt.Color(255, 255, 255));
        dashboard1.setText("Dashboard");

        manageUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageUser1.setForeground(new java.awt.Color(255, 255, 255));
        manageUser1.setText("Manage User");
        manageUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUser1MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("===MENUS===");

        foodMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        foodMenu1.setForeground(new java.awt.Color(255, 255, 255));
        foodMenu1.setText("Makanan");
        foodMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodMenu1MouseClicked(evt);
            }
        });

        drinkMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        drinkMenu1.setForeground(new java.awt.Color(1, 255, 163));
        drinkMenu1.setText("Minuman");
        drinkMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinkMenu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageUser1)
                            .addComponent(dashboard1)
                            .addComponent(foodMenu1)
                            .addComponent(drinkMenu1)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dashboard1)
                        .addGap(18, 18, 18)
                        .addComponent(manageUser1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(16, 16, 16)
                        .addComponent(foodMenu1)
                        .addGap(18, 18, 18)
                        .addComponent(drinkMenu1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void selectDrinks() {
        var listDrinks = crudDrink.select();
        model.setRowCount(0);
        for (int i = 0; i < listDrinks.size(); i++) {
            var drinkList = listDrinks.get(i);
            Object[] obj = {drinkList.getKode_drink(), drinkList.getName(), drinkList.getStock(), drinkList.getPrice(), drinkList.getCategory()};
            model.addRow(obj);
        }
    }

    public void clearField() {
        idDrink.setText("");
        drinkName.setText("");
        drinkPrice.setText("");
        drinkCategories.setSelectedItem("Teh");
        drinkStock.setSelectedItem("Kosong");
    }


    private void drinkCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkCategoriesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void drinkStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkStockActionPerformed

    private void btnDrinkAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkAddActionPerformed
        // TODO add your handling code here:
        if (idDrink.getText().isEmpty() || drinkName.getText().isEmpty() || drinkPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
            return;
        };

        String categoryStr = drinkCategories.getSelectedItem().toString();
        String stockStr = drinkStock.getSelectedItem().toString();

        crudDrink.insert(idDrink.getText(), drinkName.getText(), stockStr, Integer.parseInt(drinkPrice.getText()), categoryStr);
        selectDrinks();
        clearField();

    }//GEN-LAST:event_btnDrinkAddActionPerformed

    private void drinkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinkTableMouseClicked
        // TODO add your handling code here:
        int tableIndex = drinkTable.getSelectedRow();
        idDrink.setEditable(false);
        idDrink.setBackground(Color.lightGray);
        idDrink.setText(model.getValueAt(tableIndex, 0).toString());
        drinkName.setText(model.getValueAt(tableIndex, 1).toString());
        drinkStock.setSelectedItem(model.getValueAt(tableIndex, 2).toString());
        drinkPrice.setText(model.getValueAt(tableIndex, 3).toString());
        drinkCategories.setSelectedItem(model.getValueAt(tableIndex, 4).toString());
    }//GEN-LAST:event_drinkTableMouseClicked

    private void btnDrinkDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkDeleteActionPerformed
        // TODO add your handling code here:
        int tableIndex = drinkTable.getSelectedRow();
        String id_kode = model.getValueAt(tableIndex, 0).toString();

        idDrink.setEditable(true);
        idDrink.setBackground(Color.WHITE);

        crudDrink.delete(id_kode);
        selectDrinks();
        clearField();
    }//GEN-LAST:event_btnDrinkDeleteActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnDrinkEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkEditActionPerformed
        // TODO add your handling code here:
        int tableIndex = drinkTable.getSelectedRow();
        String id_kode = model.getValueAt(tableIndex, 0).toString();

        idDrink.setEditable(true);
        idDrink.setBackground(Color.WHITE);

        if (idDrink.getText().isEmpty() || drinkName.getText().isEmpty() || drinkPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
            return;
        };

        String categoryStr = drinkCategories.getSelectedItem().toString();
        String stockStr = drinkStock.getSelectedItem().toString();

        crudDrink.update(id_kode, drinkName.getText(), stockStr, Integer.parseInt(drinkPrice.getText()), categoryStr);
        selectDrinks();
        clearField();
    }//GEN-LAST:event_btnDrinkEditActionPerformed

    private void btnDrinkClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkClearActionPerformed
        // TODO add your handling code here:
        clearField();
        idDrink.setEditable(true);
        idDrink.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDrinkClearActionPerformed

    private void foodMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMenu1MouseClicked
        // TODO add your handling code here:
        new AdminFoodScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_foodMenu1MouseClicked

    private void drinkMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinkMenu1MouseClicked
        // TODO add your handling code here:
        new AdminDrinkScreen().setVisible(true);
    }//GEN-LAST:event_drinkMenu1MouseClicked

    private void manageUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUser1MouseClicked
        // TODO add your handling code here:
        new AdminManageUserScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageUser1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDrinkScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDrinkScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDrinkScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDrinkScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDrinkScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrinkAdd;
    private javax.swing.JButton btnDrinkClear;
    private javax.swing.JButton btnDrinkDelete;
    private javax.swing.JButton btnDrinkEdit;
    private javax.swing.JLabel dashboard1;
    private javax.swing.JComboBox<String> drinkCategories;
    private javax.swing.JLabel drinkMenu1;
    private javax.swing.JTextField drinkName;
    private javax.swing.JTextField drinkPrice;
    private javax.swing.JComboBox<String> drinkStock;
    private javax.swing.JTable drinkTable;
    private javax.swing.JLabel foodMenu1;
    private javax.swing.JTextField idDrink;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageUser1;
    private javax.swing.JTextField username2;
    private javax.swing.JTextField username3;
    // End of variables declaration//GEN-END:variables
}
